register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('', views.register, name="form"),
]

tp1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include, re_path
from register.views import register
from django.contrib.auth import views
from landingpage.views import landingpage
from registersuccess.views import registersuccess
from daftardonasi.views import daftardonasi
import campaignpage
from donation.views import formdonation
import tp1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace="social")),
    path('', include('donation.urls'), name="index"),
    path('register/', include('register.urls')),
    path('register/success/', registersuccess, name='registersuccess'),
    path('', include('landingpage.urls')),
    path('', include('campaignpage.urls')),
    path('', include('logingoogle.urls')),
    path('', include('aboutus.urls')),
    path('', include('daftardonasi.urls')),
]

register/models.py
from django.db import models

# Create your models here.

class Register(models.Model):
    name = models.CharField(max_length=100)
    birthdate = models.DateField(blank=True, null=True)
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=100)

    def __str__(self):
        return self.name

register/forms.py
from django import forms

class RegistrationForm(forms.Form):
    name = forms.CharField(label='Full Name\t:', required=True, max_length=100)
    birthdate = forms.DateField(label="Birth Date\t:", required=True, input_formats=['%Y-%m-%d'],
                           widget=forms.DateInput(attrs={'type': 'date'}))
    email = forms.EmailField(label='Email\t\t:', required=True, max_length=100)
    password = forms.CharField(label='Password\t:', required=True, widget=forms.PasswordInput)

register/views.py
from django.shortcuts import render, redirect
from .forms import RegistrationForm
from .models import Register

# Create your views here.

def register(request):
    form = RegistrationForm(request.POST or None)
    response = {}
    if request.method == "POST":
        if form.is_valid():
            data = form.cleaned_data
            name = request.POST.get('name')
            birthdate = request.POST.get('birthdate')
            email = request.POST.get('email')
            password = request.POST.get('password')
            Register.objects.create(**data)
            print(name, birthdate, email, password)
            return redirect('success/')

        else:
            return render(request, 'register.html', response)

    else:
        register = Register.objects.all()
        response['form'] = form
        response['register'] = register
        return render(request, 'register.html', response)

register/templates/register.html
{% load static %}
{% load crispy_forms_tags %}
<!doctype html>
<html>
  <head>
    <title>Register</title>
    <link href="https://fonts.googleapis.com/css?family=Lato:400i|Roboto" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
  </head>
  <body style="background-color: #FCFCFC">
    <div class="header">
      {% include 'header.html' %}
    </div>

    <div class="yuhu">
      <p class="titleText" style="margin-left: 30%; margin-top:10%; font-size: 30px">REGISTER</p>
      <div class="bodyText" style="margin-left: 30%; margin-right: auto">
        <form id="form" method="POST" action="{% url 'register:form' %}" class="formText">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success registerbtn btn-lg" value="submit">REGISTER</button>
        </form>
      </div>
    </div>
    <div class="footer customFooter">
      {% include 'footer.html' %}
    </div>
  </body>
  </html>