donation/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'donation'

urlpatterns = [
    path('formdonation', views.formdonation, name="formdonation"),
    path('formdonation/adddonatur', views.adddonatur, name="adddonatur"),
    path('formdonation/donationsuccess', views.donationsuccess, name="donationsuccess")
]

tp1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include, re_path
from register.views import register
from django.contrib.auth import views
from landingpage.views import landingpage
from registersuccess.views import registersuccess
from daftardonasi.views import daftardonasi
import campaignpage
from donation.views import formdonation
import tp1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace="social")),
    path('', include('donation.urls'), name="index"),
    path('register/', include('register.urls')),
    path('register/success/', registersuccess, name='registersuccess'),
    path('', include('landingpage.urls')),
    path('', include('campaignpage.urls')),
    path('', include('logingoogle.urls')),
    path('', include('aboutus.urls')),
    path('', include('daftardonasi.urls')),
]

donation/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

#allow_choices = [(1,'Allow to show my name as a donatur in the campaign')]

class DonaturEvent(models.Model):
	namaprogram = models.CharField(max_length=200)
	nama = models.CharField(max_length=200)
	email = models.CharField(max_length=200)
	amount = models.BigIntegerField(validators=[MinValueValidator(0), MaxValueValidator(999999999999999)])
	allow = models.BooleanField()
	time = models.DateTimeField(auto_now_add=True)

donation/forms.py
from django import forms
from .models import DonaturEvent

class DonaturEventForm(forms.Form):
	text_attrs = {
		'id': 'id_donation',
		'type': 'text',
		'class': 'donation-form-input'
	}


	email_attrs = {
		'id': 'id_donation',
		'type': 'email',
		'class': 'donation-form-input'
	}

	number_attrs = {
		'id': 'id_donation',
		'type': 'number',
		'class': 'donation-form-input'
	}
	checkbox_attrs = {
		'id': 'id_checkbox',
		'type': 'checkbox',
		'class': 'donation-form-input'
	}


	namaprogram = forms.CharField(widget=forms.TextInput(attrs=text_attrs), label="", required=True)
	amount = forms.IntegerField(widget=forms.NumberInput(attrs=number_attrs), label="", required=True)
	allow = forms.BooleanField(widget=forms.CheckboxInput(attrs=checkbox_attrs), required=False)

donation/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import DonaturEventForm
from .models import DonaturEvent

# Create your views here.
response = {}
def formdonation(request):    
    response['author'] = "" #TODO Implement yourname
    alldonatur = DonaturEvent.objects.all()
    response['alldonatur'] = alldonatur
    html = 'formdonation.html'
    response['donation_form'] = DonaturEventForm
    return render(request, html, response)

def adddonatur(request):
    form = DonaturEventForm(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['namaprogram'] = request.POST['namaprogram']
        response['nama'] = request.user.username
        response['email'] = request.user.email
        response['amount'] = request.POST['amount']
        if  'allow' in request.POST:
        	response['allow'] = True # pragma: no cover
        else:
        	response['allow'] = False
        donatur = DonaturEvent(namaprogram=response['namaprogram'], nama=response['nama'],
        	email=response['email'], amount=response['amount'], allow=response['allow'])
        donatur.save()
        return HttpResponseRedirect('/formdonation/donationsuccess')
    else:
        return HttpResponseRedirect('/formdonation')

def donationsuccess(request):
    return render(request, 'donationsuccess.html')

donation/templates/donationsuccess.html
{% load static %}
<!doctype html>
<html>
  <head>
    <title>Successfully registered</title>
    <link href="https://fonts.googleapis.com/css?family=Lato:400i|Roboto" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/donation.css' %}">
    <script>
    'use strict';

      // If set to true, the user must press
      // UP UP DOWN ODWN LEFT RIGHT LEFT RIGHT A B
      // to trigger the confetti with a random color theme.
      // Otherwise the confetti constantly falls.
      var onlyOnKonami = false;

      $(function() {
      // Globals
      var $window = $(window)
        , random = Math.random
        , cos = Math.cos
        , sin = Math.sin
        , PI = Math.PI
        , PI2 = PI * 2
        , timer = undefined
        , frame = undefined
        , confetti = [];

      // Settings
      var konami = [38, 38, 40, 40, 37, 39, 37, 39, 66, 65]
        , pointer = 0;

      var particles = 150
        , spread = 40
        , sizeMin = 3
        , sizeMax = 12 - sizeMin
        , eccentricity = 10
        , deviation = 100
        , dxThetaMin = -.1
        , dxThetaMax = -dxThetaMin - dxThetaMin
        , dyMin = .13
        , dyMax = .18
        , dThetaMin = .4
        , dThetaMax = .7 - dThetaMin;

      var colorThemes = [
        function() {
          return color(200 * random()|0, 200 * random()|0, 200 * random()|0);
        }, function() {
          var black = 200 * random()|0; return color(200, black, black);
        }, function() {
          var black = 200 * random()|0; return color(black, 200, black);
        }, function() {
          var black = 200 * random()|0; return color(black, black, 200);
        }, function() {
          return color(200, 100, 200 * random()|0);
        }, function() {
          return color(200 * random()|0, 200, 200);
        }, function() {
          var black = 256 * random()|0; return color(black, black, black);
        }, function() {
          return colorThemes[random() < .5 ? 1 : 2]();
        }, function() {
          return colorThemes[random() < .5 ? 3 : 5]();
        }, function() {
          return colorThemes[random() < .5 ? 2 : 4]();
        }
      ];
      function color(r, g, b) {
        return 'rgb(' + r + ',' + g + ',' + b + ')';
      }

      // Cosine interpolation
      function interpolation(a, b, t) {
        return (1-cos(PI*t))/2 * (b-a) + a;
      }

      // Create a 1D Maximal Poisson Disc over [0, 1]
      var radius = 1/eccentricity, radius2 = radius+radius;
      function createPoisson() {
        // domain is the set of points which are still available to pick from
        // D = union{ [d_i, d_i+1] | i is even }
        var domain = [radius, 1-radius], measure = 1-radius2, spline = [0, 1];
        while (measure) {
          var dart = measure * random(), i, l, interval, a, b, c, d;

          // Find where dart lies
          for (i = 0, l = domain.length, measure = 0; i < l; i += 2) {
            a = domain[i], b = domain[i+1], interval = b-a;
            if (dart < measure+interval) {
              spline.push(dart += a-measure);
              break;
            }
            measure += interval;
          }
          c = dart-radius, d = dart+radius;

          // Update the domain
          for (i = domain.length-1; i > 0; i -= 2) {
            l = i-1, a = domain[l], b = domain[i];
            // c---d          c---d  Do nothing
            //   c-----d  c-----d    Move interior
            //   c--------------d    Delete interval
            //         c--d          Split interval
            //       a------b
            if (a >= c && a < d)
              if (b > d) domain[l] = d; // Move interior (Left case)
              else domain.splice(l, 2); // Delete interval
            else if (a < c && b > c)
              if (b <= d) domain[i] = c; // Move interior (Right case)
              else domain.splice(i, 0, c, d); // Split interval
          }

          // Re-measure the domain
          for (i = 0, l = domain.length, measure = 0; i < l; i += 2)
            measure += domain[i+1]-domain[i];
        }

        return spline.sort();
      }

      // Create the overarching container
      var container = document.createElement('div');
      container.style.position = 'fixed';
      container.style.top      = '0';
      container.style.left     = '0';
      container.style.width    = '100%';
      container.style.height   = '0';
      container.style.overflow = 'visible';
      container.style.zIndex   = '9999';

      // Confetto constructor
      function Confetto(theme) {
        this.frame = 0;
        this.outer = document.createElement('div');
        this.inner = document.createElement('div');
        this.outer.appendChild(this.inner);

        var outerStyle = this.outer.style, innerStyle = this.inner.style;
        outerStyle.position = 'absolute';
        outerStyle.width  = (sizeMin + sizeMax * random()) + 'px';
        outerStyle.height = (sizeMin + sizeMax * random()) + 'px';
        innerStyle.width  = '100%';
        innerStyle.height = '100%';
        innerStyle.backgroundColor = theme();

        outerStyle.perspective = '50px';
        outerStyle.transform = 'rotate(' + (360 * random()) + 'deg)';
        this.axis = 'rotate3D(' +
          cos(360 * random()) + ',' +
          cos(360 * random()) + ',0,';
        this.theta = 360 * random();
        this.dTheta = dThetaMin + dThetaMax * random();
        innerStyle.transform = this.axis + this.theta + 'deg)';

        this.x = $window.width() * random();
        this.y = -deviation;
        this.dx = sin(dxThetaMin + dxThetaMax * random());
        this.dy = dyMin + dyMax * random();
        outerStyle.left = this.x + 'px';
        outerStyle.top  = this.y + 'px';

        // Create the periodic spline
        this.splineX = createPoisson();
        this.splineY = [];
        for (var i = 1, l = this.splineX.length-1; i < l; ++i)
          this.splineY[i] = deviation * random();
        this.splineY[0] = this.splineY[l] = deviation * random();

        this.update = function(height, delta) {
          this.frame += delta;
          this.x += this.dx * delta;
          this.y += this.dy * delta;
          this.theta += this.dTheta * delta;

          // Compute spline and convert to polar
          var phi = this.frame % 7777 / 7777, i = 0, j = 1;
          while (phi >= this.splineX[j]) i = j++;
          var rho = interpolation(
            this.splineY[i],
            this.splineY[j],
            (phi-this.splineX[i]) / (this.splineX[j]-this.splineX[i])
          );
          phi *= PI2;

          outerStyle.left = this.x + rho * cos(phi) + 'px';
          outerStyle.top  = this.y + rho * sin(phi) + 'px';
          innerStyle.transform = this.axis + this.theta + 'deg)';
          return this.y > height+deviation;
        };
      }

      function poof() {
        if (!frame) {
          // Append the container
          document.body.appendChild(container);

          // Add confetti
          var theme = colorThemes[onlyOnKonami ? colorThemes.length * random()|0 : 0]
            , count = 0;
          (function addConfetto() {
            if (onlyOnKonami && ++count > particles)
              return timer = undefined;

            var confetto = new Confetto(theme);
            confetti.push(confetto);
            container.appendChild(confetto.outer);
            timer = setTimeout(addConfetto, spread * random());
          })(0);

          // Start the loop
          var prev = undefined;
          requestAnimationFrame(function loop(timestamp) {
            var delta = prev ? timestamp - prev : 0;
            prev = timestamp;
            var height = $window.height();

            for (var i = confetti.length-1; i >= 0; --i) {
              if (confetti[i].update(height, delta)) {
                container.removeChild(confetti[i].outer);
                confetti.splice(i, 1);
              }
            }

            if (timer || confetti.length)
              return frame = requestAnimationFrame(loop);

            // Cleanup
            document.body.removeChild(container);
            frame = undefined;
          });
        }
      }

      $window.keydown(function(event) {
        pointer = konami[pointer] === event.which
          ? pointer+1
          : +(event.which === konami[0]);
        if (pointer === konami.length) {
          pointer = 0;
          poof();
        }
      });

      if (!onlyOnKonami) poof();
      });


    </script>
  </head>
  <body style="background-color: #FCFCFC">
    <div class="header">
      {% include 'header.html' %}
    </div>

    <div>
      <br><br><br>
      <p class="bodyText" style="text-align: center; font-size: 20px; font-family: Lato; padding-top: 10%;">You have successfully donated.<br>Thank you.</p>
    </div>
      
    <div class="footer" style="padding-top: 200px;">
      {% include 'footer.html' %}
    </div>
  </body>
  </html>

donation/templates/formdonation.html
{% load static %}
<!doctype html>
<html>
  <head>
    <title>Form Donation</title>
    <link href="https://fonts.googleapis.com/css?family=Lato|Roboto" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/donation.css' %}">
  </head>
  <body style="background-color: #FCFCFC">
    <div>
      {% include 'header.html' %}
    </div>
    <div class="row">
      <br><br><br><br><br><br><br>
    </div>
    <div class="row">
      <div class="col-3">
        <p></p>
      </div>
      <div class="col-9">
        <div class="container-form">
          <div class="padding">
            <h3 class="titleText">Let's Donate !</h3>
            <br>
            <form action="{% url 'donation:adddonatur' %}" method="POST" style="font-size: 20px;">
                {% csrf_token %}
                <p class="text-form-donation" style="font-weight: bold;">Which Campaign?</p>
                <p style="font-family: 'Lato'; font-size: 14px; color:black;">(Ayo Bantu Palu-Donggala/Ulurkan Tangan untuk Lombok/Bantu Korban Tsunami Palu-Donggala/Bantu Anak-Anak Korban Gempa Lombok)</p>
                {{ donation_form.namaprogram }} <br>
                <p class="text-form-donation">Amount of Donate</p>
                {{ donation_form.amount }} <br><br>
                <span>{{ donation_form.allow }}</span><span style="font-family: 'Lato'; font-size: 15px;">Allow to show my name as a donatur in the campaign</span>  <br><br>
                <input type="submit" value="DONATE NOW" class="btn btn-basic button-post" style="color:white; font-size: 14px;">
            </form>
          </div>
        </div>
      </div>
    </div>
    <br><br><br><br><br><br><br><br><br>
    <div>
      <footer class="footer customFooter">
        {% include 'footer.html' %}
      </footer>
    </div>
  </body>
  </html>