aboutus/urls.py
from django.urls import path
from . import views
from .views import aboutus, testimoniPost

app_name = 'aboutus'

urlpatterns = [
    path('aboutus/', views.aboutus, name='aboutus'),
    path('testimonipost/', views.testimoniPost, name='testimonipost'),
]

donation/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'donation'

urlpatterns = [
    path('formdonation', views.formdonation, name="formdonation"),
    path('formdonation/adddonatur', views.adddonatur, name="adddonatur"),
    path('formdonation/donationsuccess', views.donationsuccess, name="donationsuccess")
]

landingpage/urls.py
from django.urls import path
from . import views
from .views import landingpage

app_name = 'landingpage'

urlpatterns = [
	path('', views.landingpage, name = 'landingpage')
]

logingoogle/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'logingoogle'

urlpatterns = [
    path('logout/', views.logoutView, name="logout"),
]

tp1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include, re_path
from register.views import register
from django.contrib.auth import views
from landingpage.views import landingpage
from registersuccess.views import registersuccess
from daftardonasi.views import daftardonasi
import campaignpage
from donation.views import formdonation
import tp1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace="social")),
    path('', include('donation.urls'), name="index"),
    path('register/', include('register.urls')),
    path('register/success/', registersuccess, name='registersuccess'),
    path('', include('landingpage.urls')),
    path('', include('campaignpage.urls')),
    path('', include('logingoogle.urls')),
    path('', include('aboutus.urls')),
    path('', include('daftardonasi.urls')),
]

templates/footer.html
{% load static %}
<!doctype html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Lato:400i|Roboto" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
  </head>
  <div class="footer customFooter">
    <footer class="page-footer font-small unique-color-dark customFooter">
        <!-- Footer Links -->
      <div class="container text-center text-md-left mt-5">

        <!-- Grid row -->
        <div class="row mt-3">

          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">

            <!-- Content -->
              <a class="navbar-brand" href="{% url 'landingpage'}">
                <img src="{% static 'images/logo.png' %}" alt="Logo" style="width:150px;">
              </a>
            <p class="footerText" style="display: flex;">no one is useless in this world who lightens the burdens of another <br><br>- Charles Dickens</p>`

          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">

            <!-- Links -->
            <h6 class="text-uppercase font-weight-bold titleText" style="color: #FCFCFC;">RECENT POSTS</h6>
            <hr class="accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 120px; background-color: #FCFCFC">
            <p class="footerText">
              <a href="{% url 'landingpage:landingpage' %}#campaigns">CAMPAIGNS</a>
            </p>
            <p class="footerText">
              <a href="#">GALLERY</a>
            </p>
            <p class="footerText">
              <a href="#">VIDEOS</a>
            </p>
            <p class="footerText">
              <a href="{% url 'landingpage:landingpage' %}#news">NEWS</a>
            </p>

          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

            <!-- Links -->
            <h6 class="text-uppercase font-weight-bold titleText" style="color: #FCFCFC;">CONTACT US</h6>
            <hr class="accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 105px; background-color: #FCFCFC">
            <p class="footerText">
              Jalan Margonda Raya, Pondok Cina, Beji, Kota Depok, Jawa Barat 16424
            </p>

            <p class="footerText">
              +62 21 14045
            </p>

          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4 maps">

            <!-- Map -->
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3965.225966297407!2d106.82695273971761!3d-6.364795413629866!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e69ec19efd057d7%3A0xac569bb299fecc42!2sGedung+A+FASILKOM+UI!5e0!3m2!1sen!2sid!4v1539610263110" width="200" height="200" frameborder="0" style="border:0; margin-left: 10%;" allowfullscreen></iframe>

          </div>
          <!-- Grid column -->

        </div>
        <!-- Grid row -->

      </div>
      <!-- Footer Links -->

    </footer>
    <!-- Footer -->
  </div>
</html>

templates/header.html
{% load static %}
<!doctype html>
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/png" href="{% static 'favicon-32x32.png' %}" sizes="32x32" />
  <link rel="icon" type="image/png" href="{% static 'favicon-16x16.png' %}" sizes="16x16" />
  <link href="https://fonts.googleapis.com/css?family=Lato:400i|Roboto" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
    crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script>
    $(document).ready(function(){
      $("#go-to-news").click(function () {
        $('html, body').animate({
            scrollTop: $("#news").offset().top
        }, 800);
      });

      $("#go-to-campaigns").click(function () {
        $('html, body').animate({
            scrollTop: $("#campaigns").offset().top
        }, 800);
      });

      // Add smooth scrolling to all links
      $("a").on('click', function(event) {

        // Make sure this.hash has a value before overriding default behavior
        if (this.hash !== "") {
          // Prevent default anchor click behavior
          event.preventDefault();

          // Store hash
          var hash = this.hash;

          // Using jQuery's animate() method to add smooth page scroll
          // The optional number (800) specifies the number of milliseconds it takes to scroll to the specified area
          $('html, body').animate({
            scrollTop: $(hash).offset().top
          }, 800, function(){

            // Add hash (#) to URL when done scrolling (default click behavior)
            window.location.hash = hash;
          });
        } // End if
      });
    });
    </script>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
  <div class="header">
    <nav id="nav" class="navbar navbar-expand-sm customNavbar fixed-top" style="background-color: #15724d;">
      <a class="navbar-brand" href="{% url 'landingpage:landingpage' %}">
        <img src="{% static 'images/logo.png' %}" alt="Logo" style="width:150px;">
      </a>
      <!-- Toggler/collapsibe Button -->
      <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="collapsibleNavbar">
        <ul class="navbar-nav">
          {% if user.is_authenticated %}
          <li class="nav-item navbarText">
            <a class="nav-link" href="{% url 'daftardonasi:daftardonasi' %}">Hello, {{ user.username }}</a>
          </li>
          <li class="nav-item navbarText">
            <a class="nav-link" href="{% url 'aboutus:aboutus' %}">ABOUT US</a>
          </li>
          <li class="nav-item navbarText">
            <a class="nav-link" href="{% url 'donation:formdonation' %}">DONATE</a>
          </li>
          <li class="nav-item navbarText">
            <a class="nav-link" href="{% url 'landingpage:landingpage' %}#campaigns" id="go-to-campaigns">CAMPAIGNS</a>
          </li>
          <li class="nav-item navbarText">
            <a class="nav-link" href="{% url 'landingpage:landingpage' %}#news" id="go-to-news">NEWS</a>
          </li>

          <li class="nav-item navbarText">
            <a class="nav-link" href="{% url 'logingoogle:logout' %}">LOGOUT</a>
          </li>
          {% else %}
          <li class="nav-item navbarText">
            <a class="nav-link" href="{% url 'aboutus:aboutus' %}">ABOUT US</a>
          </li>
          <li class="nav-item navbarText">
            <a class="nav-link" href="{% url 'social:begin' 'google-oauth2' %}">DONATE</a>
          </li>
          <li class="nav-item navbarText">
            <a class="nav-link" href="{% url 'landingpage:landingpage' %}#campaigns" id="go-to-campaigns">CAMPAIGNS</a>
          </li>
          <li class="nav-item navbarText">
            <a class="nav-link" href="{% url 'landingpage:landingpage' %}#news" id="go-to-news">NEWS</a>
          </li>
          <li class="nav-item navbarText">
            <a class="nav-link" href="{% url 'social:begin' 'google-oauth2' %}">LOGIN</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </div>
</head>

</html>